### PR TITLE
Newkaku cover defaults to InvertedRflinkCover

### PR DESCRIPTION
**Pull request by javicalle**
IMO it's more clear than if/else statements

### CODE REVIEW

**Comment by javicalle** [comment]
Arrrg!
I wanted to make different PR that you could accept or reject individually, but in the end it seems that you will all get together here. Sorry for the inconvenience

My second commit "Autoresolve type for newkaku" will be a **breaking change**.
If we assume that **all newkaku covers** have the same behavior because they are configured as ON-->OPEN & OFF-->CLOSE, this piece of code will be OK. This same assumption is made with the [newkaku lights](https://github.com/home-assistant/home-assistant/blob/3b0660ae896d89e339d19634bf909815dbff1304/homeassistant/components/rflink/light.py#L61).
Before this change, nobody will use the InvertedRflinkCover if it is not configured explicitly with `type: inverted`. As you can see, this change will apply the inverted type to all the `newkaku` covers.

Somewhere I had read that it is preferable to define the default behavior (for a device type), instead of forcing the user to configure it. The doubt in my case is knowing what is the most widespread or default behavior with the `newkaku` covers. If you ask me, I would bet on the implementation that I propose, but you should be the one who has the last word. 
Feel free to make your choice.

**Comment by fmartens** [comment]
@javicalle , Sorry for the delay. I like the auto-resolve idea but we need to mention this behavior in the documentation. I will test your code over the weekend and merge your pull request when done testing. I will also update the test cases.

**Comment by javicalle** [comment]
No problem.
I can also help you with the tests.

**Comment by fmartens** [comment]
I really don't know how many people are using the ASUN-650 and I really don't know how many people actually rewired their ASUN-650 devices so that they respond properly to the home-assistant buttons. I will merge your request and I will ask all involved in the discussion of bug 10810 if they don't mind the new behavior.

**Pull request merged**
